### ISSUE TITLE
PWA: SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by stuta** [vueneue/vueneue#14]
Create clean vue-cli 3.0.0-rc.10 project and then ```vue add @vueneue/ssr```. Start with ```yarn ssr:serve```. Open http://127.0.0.1:8080 in bowser.

.../node_modules/register-service-worker/index.js:18
export function register (swUrl, hooks) {
^^^^^^

SyntaxError: Unexpected token export

**Comment by chymz** [comment]
Hi,

Did you use official PWA cli plugin, or have a custom code for your service worker ?

**Comment by stuta** [comment]
Clean official  vue-cli 3.0.0-rc.10 projet ```vue create ssr```, (vue-router, vuex, sass, babel, pwa, eslint, unit-jest, e2e-cypress), no changes in it.

**Comment by chymz** [comment]
OK, I know this issue.

As simple workaround, in `src/main.js`, just replace:

```js
import "./registerServiceWorker";
```

By 

```js
if (process.client) require("./registerServiceWorker");
```

**Comment by stuta** [comment]
Thanks, now it works.

**Comment by chymz** [comment]
I keep this open, this plugin need to handle this behavior ;)

**Comment by chymz** [comment]
Fixed in `0.3.13`

**Comment by mapsgeek** [comment]
@chymz  i still get this error on 0.3.13
![screencapture-localhost-8000-plugins-2018-08-09-10_04_13](https://user-images.githubusercontent.com/10188264/43886403-e3bb9110-9bbb-11e8-8b20-8610c04ec675.png)

**Comment by chymz** [comment]
This screenshot doesn't help me... can you share the code arround your import of `registerServiceWorker` ?

**Comment by mapsgeek** [comment]
this is from main.js, fresh installation just the plugins 

```
import Vue from 'vue'
import App from './App.vue'
import './registerServiceWorker'
import store from './store'

Vue.config.productionTip = false

export default ({ router, store }) => {
  return new Vue({
    store,
    router,
    render: h => h(App)
  });
}

```

**Comment by chymz** [comment]
You can apply: https://github.com/vueneue/vueneue/issues/14#issuecomment-410237573

I will fix this soon

**Comment by mapsgeek** [comment]
applying [#14 (comment)](https://github.com/vueneue/vueneue/issues/14#issuecomment-410237573)
brings an error of 

`TypeError: Object(...) is not a function
    at createContext (webpack-internal:///./node_modules/@vueneue/ssr-core/utils/context.js:16:74)
    at __webpack_exports__.default (webpack-internal:///./node_modules/@vueneue/ssr-core/server/index.js:18:87)
    at C:\Users\ibrah\Desktop\work\farcloser\node_modules\vue-server-renderer\build.js:8437:15
    at new Promise (<anonymous>)
    at C:\Users\ibrah\Desktop\work\farcloser\node_modules\vue-server-renderer\build.js:8399:14
    at Object.renderToString (C:\Users\ibrah\Desktop\work\farcloser\node_modules\vue-server-renderer\build.js:8575:9)
    at Promise (C:\Users\ibrah\Desktop\work\farcloser\node_modules\@vueneue\ssr-server\lib\renderRoute.js:19:35)
    at new Promise (<anonymous>)
    at module.exports (C:\Users\ibrah\Desktop\work\farcloser\node_modules\@vueneue\ssr-server\lib\renderRoute.js:6:10)
    at readyPromise.then (C:\Users\ibrah\Desktop\work\farcloser\node_modules\@vueneue\ssr-server\lib\index.js:74:38)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

**Comment by chymz** [comment]
It seems that plugin have not been invoked correctly...

Can you try to call `vue invoke @vueneue/ssr` ?

Some files need to follow this: https://vueneue.github.io/docs/guide/start.html#base-files-code-structure

**Comment by mapsgeek** [comment]
thank you, the work around works just fine now :)
